[package]
name = "flappy-ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui-macroquad = "0.15.0"
macroquad = "0.3.25"
once_cell = "1.17.1"
rand = "0.8.5"
